set -g @plugin 'omerxx/tmux-sessionx'
set -g @sessionx-custom-paths '/home/matvey/dev,/home/matvey/dev/work,/home/matvey/dev/projects,/home/matvey/dev/sandbox,/home/matvey/dev/oss'
set -g @sessionx-fzf-builtin-tmux 'on'
set -g @sessionx-ls-command 'eza'
set -g @sessionx-bind "f"
set -g @sessionx-preview-enabled 'false'
set -g @sessionx-custom-paths-subdirectories 'true'
set -g @sessionx-window-height '50%'
set -g @sessionx-window-width '50%'
set -g @sessionx-additional-options '--color=bg+:#313244,bg:#1E1E2E,spinner:#F5E0DC,hl:#F38BA8 \
--color=fg:#CDD6F4,header:#F38BA8,info:#CBA6F7,pointer:#F5E0DC \
--color=marker:#B4BEFE,fg+:#CDD6F4,prompt:#CBA6F7,hl+:#F38BA8 \
--color=selected-bg:#45475A \
--color=border:#6C7086,label:#CDD6F4'

set -g mouse on
set -g default-terminal "tmux-256color"
set -s escape-time 0
set -g history-limit 50000
set -g display-time 4000
set -g status-interval 5
set -g focus-events on
set -g base-index 1
set -g status-position bottom
set -g renumber-windows on
set -s set-clipboard on
set -g extended-keys on
set -g extended-keys-format csi-u

set -g default-shell /usr/bin/fish

set -g prefix C-a
bind C-a send-prefix
bind a last-window

set -g @ctp_bg "#181825"
set -g @ctp_surface_1 "#494d64"
set -g @ctp_fg "#cad3f5"
set -g @ctp_mauve "#c6a0f6"
set -g @ctp_crust "#181926"

set -gF status-style "bg=#{@ctp_bg},fg=#{@ctp_fg}"

set -g status-left ""
set -g status-right ' [#S]'
set -g window-status-separator ''
set -gF window-status-format " ##I:##W "
set -gF window-status-current-format "#[bg=#{@ctp_mauve},fg=#{@ctp_crust}] ##I:##W "

unbind-key x
bind-key x kill-pane
bind-key X kill-session

bind-key g display-popup \
  -E \
  -d "#{pane_current_path}" \
  -w 90% \
  -h 90% \
  -T "lazygit" \
  lazygit

run 'tpack init'
